//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblKullanıcı
    {
        public int kullanıcıId { get; set; }
        [Required(ErrorMessage = "Lütfen Kullanıcı Adını Giriniz")]
        [Display(Name = "Kullanıcı Adı")]
        [StringLength(50, ErrorMessage = "Kullanıcı Adı 50 Karakterden Fazla Oluşamaz")]
        [RegularExpression("^[A-Za-z0-9ÜİÖĞÇüiöğç_ ]{0,50}$", ErrorMessage = "Kullanıcı Adı Özel Karakterlerden(',-,? vs.) Oluşamaz ve 50 Karakterden Fazla Olamaz")]
        public string username { get; set; }
        [Required(ErrorMessage = "Lütfen Şifre Giriniz")]
        [Display(Name = "Şifre")]
        [StringLength(50, ErrorMessage = "Şifre 20 Karakterden Fazla Oluşamaz")]
        [MinLength(6,ErrorMessage ="Şifre 6 Karakterden Az Girilemez")]
        public string password { get; set; }
        [Display(Name="Kullanıcı Rolü")]
        public Nullable<int> roleId { get; set; }
        public Nullable<System.DateTime> sonGirisTarihi { get; set; }

        [Required(ErrorMessage = "Lütfen E-mail Bilgisini Giriniz")]
        [Display(Name = "E-Mail")]
        [StringLength(50, ErrorMessage = "E-Mail 50 Karakterden Fazla Oluşamaz")]
        [RegularExpression("^[A-Za-z0-9_\\.]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Geçerli Bir Email Bilgisi Giriniz")]
        public string email { get; set; }
    
        public virtual tblRole tblRole { get; set; }
    }
}
