//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblPersonel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPersonel()
        {
            this.tblZimmet = new HashSet<tblZimmet>();
        }
    
        public int personelId { get; set; }
        [Required(ErrorMessage = "Lütfen Personel Adýný Giriniz")]
        [Display(Name = "Personel Adý")]
        [StringLength(50, ErrorMessage = "Personel Adý 50 Karakterden Fazla Oluþamaz")]
        [RegularExpression("^[A-Za-z0-9ÜÝÖÐÇüiöðç_ ]{0,50}$", ErrorMessage = "Personel Adý Özel Karakterlerden(',-,? vs.) Oluþamaz ve 50 Karakterden Fazla Olamaz")]
        public string personelAd { get; set; }
        [Required(ErrorMessage = "Lütfen Personel Soyaýný Giriniz")]
        [Display(Name = "Personel  Soyadý")]
        [StringLength(50, ErrorMessage = "Personel Adý 50 Karakterden Fazla Oluþamaz")]
        [RegularExpression("^[A-Za-z0-9ÜÝÖÐÇüiöðç_ ]{0,50}$", ErrorMessage = "Persone Soyadý Özel Karakterlerden(',-,? vs.) Oluþamaz ve 50 Karakterden Fazla Olamaz")]
        public string personelSoyad { get; set; }
        public Nullable<bool> Aktiflik { get; set; }

        [Required(ErrorMessage ="Lütfen Departman Bilgisini Giriniz")]
        [Display(Name ="Departman")]
        public Nullable<int> departmanId { get; set; }
        
        [Required(ErrorMessage = "Lütfen SGKNO Giriniz")]
        [Display(Name = "Personel SGKNO")]
        [StringLength(20, ErrorMessage = "Personel SGKNO 20 Rakamdan Fazla Oluþamaz")]
        [RegularExpression("^[A-Za-z0-9ÜÝÖÐÇüiöðç_ ]{0,20}$", ErrorMessage = "SGKNO Özel Karakterlerden(',-,? vs.) Oluþamaz ve 20 Rakamdan Fazla Olamaz")]
        public string SGKNO { get; set; }
    
        public virtual tblDepartman tblDepartman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblZimmet> tblZimmet { get; set; }
    }
}
