//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblUrun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUrun()
        {
            this.tblAtikKontrol = new HashSet<tblAtikKontrol>();
            this.tblZimmet = new HashSet<tblZimmet>();
        }
    
        public int urunId { get; set; }
        [Required(ErrorMessage = "Lütfen Ürün Adýný Giriniz")]
        [Display(Name = "Ürün Adý")]
        [StringLength(50, ErrorMessage = "Ürün Adý 50 Karakterden Fazla Oluþamaz")]
        [RegularExpression("^[A-Za-z0-9ÜÝÖÐÇüiöðç_ ]{0,50}$", ErrorMessage = "Ürün Adý Özel Karakterlerden(',-,? vs.) Oluþamaz ve 50 Karakterden Fazla Olamaz")]

        public string urunAd { get; set; }
        public Nullable<System.DateTime> urunSatinAlmaTarih { get; set; }
        [Required(ErrorMessage = "Lütfen Ürün Fiyatý Bilgisi Giriniz")]
        [Display(Name = "Ürün Fiyatý")]
        [Range(0, 10000000, ErrorMessage = "Ürün Fiyatý 0 dan Az Olamaz")]
        public Nullable<decimal> urunFiyat { get; set; }
        [Display(Name = "Parça Tipi")]
        [Required(ErrorMessage = "Lütfen Ürün Parça Tipi Bilgisi Giriniz")]
        public Nullable<int> urunParcaId { get; set; }
        public Nullable<bool> Aktiflik { get; set; }
        [Required(ErrorMessage = "Lütfen Ürünün Satýn Alýndýðý Kurum Adýný Giriniz")]
        [Display(Name = "Kurum Adý")]
        [StringLength(50, ErrorMessage = "Kurum Adý 50 Karakterden Fazla Oluþamaz")]
        [RegularExpression("^[A-Za-z0-9ÜÝÖÐÇüiöðç_ ]{0,50}$", ErrorMessage = "Kurum Adý Özel Karakterlerden(',-,? vs.) Oluþamaz ve 50 Karakterden Fazla Olamaz")]
        public string satinAlinanKurum { get; set; }
        public Nullable<bool> zimmetDurumu { get; set; }
        public int urunGenelId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAtikKontrol> tblAtikKontrol { get; set; }
        public virtual tblUrunGenel tblUrunGenel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblZimmet> tblZimmet { get; set; }
    }
}
