//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblUrunGenel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUrunGenel()
        {
            this.tblStok = new HashSet<tblStok>();
            this.tblUrun = new HashSet<tblUrun>();
        }
    
        
        public int urunGenelId { get; set; }
        [Required(ErrorMessage = "Lütfen Ürün Adını Giriniz")]
        [Display (Name ="Ürün Adı")]
        [StringLength(50,ErrorMessage ="Ürün Adı 50 Karakterden Fazla Oluşamaz")]
        [RegularExpression("^[A-Za-z0-9ÜİÖĞÇüiöğç_ ]{0,50}$",ErrorMessage ="Ürün Adı Özel Karakterlerden(',-,? vs.) Oluşamaz ve 50 Karakterden Fazla Olamaz")]
        public string urunAd { get; set; }


        public Nullable<System.DateTime> urunSatinAlmaTarih { get; set; }
        [Required(ErrorMessage ="Lütfen Ürün Fiyatı Bilgisi Giriniz")]
        [Display(Name ="Ürün Fiyatı")]
        [Range(0,10000000,ErrorMessage ="Ürün Fiyatı 0 dan Az Olamaz")]
        public Nullable<decimal> urunFiyat { get; set; }

        public Nullable<decimal> urunToplamFİyat { get; set; }

        [Display(Name ="Parça Tipi")]
        [Required(ErrorMessage ="Lütfen Ürün Parça Tipi Bilgisi Giriniz")]
        public Nullable<int> urunParcaId { get; set; }
        public Nullable<bool> Aktiflik { get; set; }

        [Required(ErrorMessage ="Lütfen Ürün Adet Bilgisini Giriniz")]
        [Display(Name ="Ürün Adeti")]
        [Range(0,100000,ErrorMessage =" Ürün Adeti 0 dan Az Olamaz")]
        public Nullable<int> urunAdet { get; set; }


        [Required(ErrorMessage = "Lütfen Ürünün Satın Alındığı Kurum Adını Giriniz")]
        [Display(Name = "Kurum Adı")]
        [StringLength(50, ErrorMessage = "Kurum Adı 50 Karakterden Fazla Oluşamaz")]
        [RegularExpression("^[A-Za-z0-9ÜİÖĞÇüiöğç_ ]{0,50}$", ErrorMessage = "Kurum Adı Özel Karakterlerden(',-,? vs.) Oluşamaz ve 50 Karakterden Fazla Olamaz")]

        public string satinAlinanKurum { get; set; }
    
        public virtual tblParcaTipi tblParcaTipi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStok> tblStok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUrun> tblUrun { get; set; }
    }
}
